/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AddCardRouteImport } from './routes/add-card'
import { Route as AddMoneyRouteImport } from './routes/add-money'
import { Route as BankTransferRouteImport } from './routes/bank-transfer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DigitalAssetsRouteImport } from './routes/digital-assets'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as RetirementRouteImport } from './routes/retirement'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SocialRouteImport } from './routes/social'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SupportRouteImport } from './routes/support'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as FeedsIndexRouteImport } from './routes/feeds/index'
import { Route as FeedsIdRouteImport } from './routes/feeds/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCardRoute = AddCardRouteImport.update({
  id: '/add-card',
  path: '/add-card',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMoneyRoute = AddMoneyRouteImport.update({
  id: '/add-money',
  path: '/add-money',
  getParentRoute: () => rootRouteImport,
} as any)
const BankTransferRoute = BankTransferRouteImport.update({
  id: '/bank-transfer',
  path: '/bank-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalAssetsRoute = DigitalAssetsRouteImport.update({
  id: '/digital-assets',
  path: '/digital-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const RetirementRoute = RetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => rootRouteImport,
} as any)
const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIndexRoute = FeedsIndexRouteImport.update({
  id: '/feeds/',
  path: '/feeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedsIdRoute = FeedsIdRouteImport.update({
  id: '/feeds/$id',
  path: '/feeds/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-card': typeof AddCardRoute
  '/add-money': typeof AddMoneyRoute
  '/bank-transfer': typeof BankTransferRoute
  '/contact': typeof ContactRoute
  '/digital-assets': typeof DigitalAssetsRoute
  '/discover': typeof DiscoverRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/retirement': typeof RetirementRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/stocks': typeof StocksRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-card': typeof AddCardRoute
  '/add-money': typeof AddMoneyRoute
  '/bank-transfer': typeof BankTransferRoute
  '/contact': typeof ContactRoute
  '/digital-assets': typeof DigitalAssetsRoute
  '/discover': typeof DiscoverRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/retirement': typeof RetirementRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/stocks': typeof StocksRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds': typeof FeedsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-card': typeof AddCardRoute
  '/add-money': typeof AddMoneyRoute
  '/bank-transfer': typeof BankTransferRoute
  '/contact': typeof ContactRoute
  '/digital-assets': typeof DigitalAssetsRoute
  '/discover': typeof DiscoverRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/operations': typeof OperationsRoute
  '/retirement': typeof RetirementRoute
  '/savings': typeof SavingsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/social': typeof SocialRoute
  '/stocks': typeof StocksRoute
  '/support': typeof SupportRoute
  '/withdraw': typeof WithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/feeds/$id': typeof FeedsIdRoute
  '/feeds/': typeof FeedsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-card'
    | '/add-money'
    | '/bank-transfer'
    | '/contact'
    | '/digital-assets'
    | '/discover'
    | '/finance'
    | '/login'
    | '/onboarding'
    | '/operations'
    | '/retirement'
    | '/savings'
    | '/settings'
    | '/signup'
    | '/social'
    | '/stocks'
    | '/support'
    | '/withdraw'
    | '/auth/callback'
    | '/feeds/$id'
    | '/feeds/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-card'
    | '/add-money'
    | '/bank-transfer'
    | '/contact'
    | '/digital-assets'
    | '/discover'
    | '/finance'
    | '/login'
    | '/onboarding'
    | '/operations'
    | '/retirement'
    | '/savings'
    | '/settings'
    | '/signup'
    | '/social'
    | '/stocks'
    | '/support'
    | '/withdraw'
    | '/auth/callback'
    | '/feeds/$id'
    | '/feeds'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-card'
    | '/add-money'
    | '/bank-transfer'
    | '/contact'
    | '/digital-assets'
    | '/discover'
    | '/finance'
    | '/login'
    | '/onboarding'
    | '/operations'
    | '/retirement'
    | '/savings'
    | '/settings'
    | '/signup'
    | '/social'
    | '/stocks'
    | '/support'
    | '/withdraw'
    | '/auth/callback'
    | '/feeds/$id'
    | '/feeds/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddCardRoute: typeof AddCardRoute
  AddMoneyRoute: typeof AddMoneyRoute
  BankTransferRoute: typeof BankTransferRoute
  ContactRoute: typeof ContactRoute
  DigitalAssetsRoute: typeof DigitalAssetsRoute
  DiscoverRoute: typeof DiscoverRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OperationsRoute: typeof OperationsRoute
  RetirementRoute: typeof RetirementRoute
  SavingsRoute: typeof SavingsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SocialRoute: typeof SocialRoute
  StocksRoute: typeof StocksRoute
  SupportRoute: typeof SupportRoute
  WithdrawRoute: typeof WithdrawRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  FeedsIdRoute: typeof FeedsIdRoute
  FeedsIndexRoute: typeof FeedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-card': {
      id: '/add-card'
      path: '/add-card'
      fullPath: '/add-card'
      preLoaderRoute: typeof AddCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-money': {
      id: '/add-money'
      path: '/add-money'
      fullPath: '/add-money'
      preLoaderRoute: typeof AddMoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-transfer': {
      id: '/bank-transfer'
      path: '/bank-transfer'
      fullPath: '/bank-transfer'
      preLoaderRoute: typeof BankTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-assets': {
      id: '/digital-assets'
      path: '/digital-assets'
      fullPath: '/digital-assets'
      preLoaderRoute: typeof DigitalAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retirement': {
      id: '/retirement'
      path: '/retirement'
      fullPath: '/retirement'
      preLoaderRoute: typeof RetirementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social': {
      id: '/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/': {
      id: '/feeds/'
      path: '/feeds'
      fullPath: '/feeds/'
      preLoaderRoute: typeof FeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feeds/$id': {
      id: '/feeds/$id'
      path: '/feeds/$id'
      fullPath: '/feeds/$id'
      preLoaderRoute: typeof FeedsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddCardRoute: AddCardRoute,
  AddMoneyRoute: AddMoneyRoute,
  BankTransferRoute: BankTransferRoute,
  ContactRoute: ContactRoute,
  DigitalAssetsRoute: DigitalAssetsRoute,
  DiscoverRoute: DiscoverRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OperationsRoute: OperationsRoute,
  RetirementRoute: RetirementRoute,
  SavingsRoute: SavingsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SocialRoute: SocialRoute,
  StocksRoute: StocksRoute,
  SupportRoute: SupportRoute,
  WithdrawRoute: WithdrawRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  FeedsIdRoute: FeedsIdRoute,
  FeedsIndexRoute: FeedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
